const countryOptions = [
    {label: "AE (United Arab Emirates)", value: "ae"},
    {label: "AT (Austria)", value: "at"},
    {label: "AU (Australia)", value: "au"},
    {label: "BE (Belgium)", value: "be"},
    {label: "CA (Canada)", value: "ca"},
    {label: "CH (Switzerland)", value: "ch"},
    {label: "CN (China)", value: "cn"},
    {label: "CZ (Czech Republic)", value: "cz"},
    {label: "DE (Germany)", value: "de"},
    {label: "DK (Denmark)", value: "dk"},
    {label: "EE (Estonia)", value: "ee"},
    {label: "ES (Spain)", value: "es"},
    {label: "EU (European Union)", value: "eu"},
    {label: "FI (Finland)", value: "fi"},
    {label: "FR (France)", value: "fr"},
    {label: "GB (United Kingdom)", value: "gb"},
    {label: "GG (Guernsey)", value: "gg"},
    {label: "GR (Greece)", value: "gr"},
    {label: "IE (Ireland)", value: "ie"},
    {label: "IS (Iceland)", value: "is"},
    {label: "IT (Italy)", value: "it"},
    {label: "JE (Jersey)", value: "je"},
    {label: "JP (Japan)", value: "jp"},
    {label: "KR (Korea)", value: "kr"},
    {label: "KI (Cayman Islands)", value: "ky"},
    {label: "LU (Luxembourg)", value: "lu"},
    {label: "LV (Latvia)", value: "lv"},
    {label: "MUL (???)", value: "mul"},
    {label: "NL (Netherlands)", value: "nl"},
    {label: "NO (Norway)", value: "no"},
    {label: "NZ (New Zealand)", value: "nz"},
    {label: "PL (Poland)", value: "pl"},
    {label: "PT (Portugal)", value: "pt"},
    {label: "SE (Sweden)", value: "se"},
    {label: "SG (Singapore)", value: "sg"},
    {label: "SK (Slovakia)", value: "sk"},
    {label: "SNA (???)", value: "sna"},
    {label: "US (United States)", value: "us"},
];

export default countryOptions;